# This is a sample .codeclimate.yml configured for Engine analysis on Code
# Climate Platform. For an overview of the Code Climate Platform, see here:
# http://docs.codeclimate.com/article/300-the-codeclimate-platform

# Under the engines key, you can configure which engines will analyze your repo.
# Each key is an engine name. For each value, you need to specify enabled: true
# to enable the engine as well as any other engines-specific configuration.

# For more details, see here:
# http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml#platform

# For a list of all available engines, see here:
# http://docs.codeclimate.com/article/296-engines-available-engines

engines:
# to turn on an engine, add it here and set enabled to `true`
# to turn off an engine, set enabled to `false` or remove it
  phpcodesniffer :
    enabled: true
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      Generic WhiteSpace DisallowTabIndent NonIndentTabsUsed:
        enabled: false
      Generic WhiteSpace ScopeIndent Incorrect:
        enabled: false
      Generic WhiteSpace ScopeIndent IncorrectExact:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration BraceOnSameLine:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration OneParamPerLine:
        enabled: false
      Squiz ControlStructures ControlSignature NewlineAfterOpenBrace:
        enabled: false
      Squiz WhiteSpace ScopeClosingBrace ContentBefore:
        enabled: false
      PSR2 Classes ClassDeclaration OpenBraceNewLine:
        enabled: false
      PSR2 Classes ClassDeclaration CloseBraceAfterBody:
        enabled: false
      PSR2 Methods FunctionCallSignature MultipleArguments:
        enabled: false
      PSR2 Methods FunctionCallSignature Indent:
        enabled: false
      PSR2 Methods FunctionCallSignature CloseBracketLine:
        enabled: false
      PSR2 Methods FunctionCallSignature ContentAfterOpenBracket:
        enabled: false
      PSR2 Methods FunctionCallSignature SpaceBeforeCloseBracket:
        enabled: false
      PSR2 Namespaces UseDeclaration SpaceAfterLastUse:
              enabled: false
  eslint:
    enabled: true
    checks:
      quotes:
        enabled: false
      no-underscore-dangle:
        enabled: false
  csslint:
    enabled: true

# Engines can analyze files and report issues on them, but you can separately
# decide which files will receive ratings based on those issues. This is
# specified by path patterns under the ratings key.

# For more details see here:
# http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml#platform

ratings:
  paths:
    - appinfo/app.php
    - config/**
    - controller/**
    - environment/**
    - http/**
    - js/**
    - middleware/**
    - preview/**
    - service/**
    - utility/**

# You can globally exclude files from being analyzed by any engine using the
# exclude_paths key.

exclude_paths:
  - '.*'
  - '.*/*'
  - '.*/**/*'
  - '*.xml'
  - '*.yml'
  - '*.lock'
  - '*.json'
  - 'appinfo/application.php'
  - 'appinfo/routes.php'
  - 'l10n/**/*'
  - 'l10n/.**/*'
  - 'vendor/**/*'
  - 'js/vendor/**/*'
  - 'templates/**/*'
  - 'css/**/*'
  - 'img/**/*'
  - 'patches/**/*'
  - 'tests/**/*'
  - 'build/**/*'
  - 'documentation/**/*'
  - 'controller/configapicontroller.php'
  - 'controller/filesapicontroller.php'
  - 'controller/previewapicontroller.php'

