languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
  - 'appinfo/application.php'
  - 'l10n/*'
  - 'js/jquery*'
  - 'js/bigshot*'
  - 'vendor/*'
  - 'js/vendor/*'
  - 'templates/*'
  - 'css/*'
  - 'img/*'
