imports:
    - php
    - javascript

filter:
    excluded_paths:
        - 'appinfo/application.php'
        - 'l10n/*'
        - 'js/jquery*'
        - 'js/bigshot*'
        - 'vendor/*'
        - 'js/vendor/*'
        - 'templates/*'
        - 'css/*'
        - 'img/*'

tools:
    sensiolabs_security_checker: true
    php_sim: true
    php_pdepend: true
    php_analyzer: true

checks:
    php:
        line_length:
            max_length: '100'
        verify_access_scope_valid: true
        require_scope_for_methods: true
        no_underscore_prefix_in_methods: true
        missing_arguments: true
        method_calls_on_non_object: true
        deprecated_code_usage: true
        no_eval: true
        parameter_doc_comments: true
        return_doc_comments: true
        fix_doc_comments: true
        return_doc_comments: true
        parameter_doc_comments: true
        more_specific_types_in_doc_comments: true
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        php5_style_constructor: true
        one_class_per_file: true
        require_php_tag_first: true
        uppercase_constants: true
        require_braces_around_control_structures: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        optional_parameters_at_the_end: true
        no_underscore_prefix_in_properties: true
        no_space_inside_cast_operator: true
        no_space_before_semicolon: true
        no_short_open_tag: true
        no_goto: true
        lowercase_php_keywords: true
        lowercase_basic_constants: true
        function_in_camel_caps: true
        classes_in_camel_caps: true
        avoid_space_indentation: true
        overriding_private_members: true
        no_unnecessary_function_call_in_for_loop: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
                size: 4
        braces:
            classes_functions:
                class: end-of-line